name: 'Complete Workflow'


on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PORT: ${{ secrets.PORT }}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  AUTH_SECRET_WORD: ${{secrets.AUTH_SECRET_WORD}}
  AUTH_EXPIRES_IN: ${{secrets.AUTH_EXPIRES_IN}}
  STORMGLASS_API_URL: ${{secrets.STORMGLASS_API_URL}}
  STORMGLASS_API_TOKEN: ${{secrets.STORMGLASS_API_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.x
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run all tests
        run: npm test
